### ISSUE TITLE
parse cityIO data and populate grid using IGeometry interface 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook_Angular_Prototype#4]

**Comment by aberke** [comment]
PR https://github.com/CityScope/CSL_Hamburg_Grasbrook_Angular_Prototype/pull/7 parses cityIO data and populates map.
Still TODO: properly rotate grid data

**Comment by RELNO** [comment]
@aberke great, looking into rotation now

**Comment by RELNO** [comment]
updates are done at https://github.com/CityScope/CSL_Hamburg_Grasbrook_Angular_Prototype/commit/c231f3fb4b73faddd8040ebe8d39e25c325ecaad

populating grid is discussed at https://github.com/CityScope/CSL_Hamburg_Grasbrook_Angular_Prototype/issues/8

closing.
