### ISSUE TITLE
Better naming for interfaces

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Hamburg_Grasbrook_Angular_Prototype#5]
IGeometry, IGeoJson can easily confuse

**Comment by aberke** [comment]
These names were meant to correspond with the names and definitions of the GeoJSON format.  Check out http://geojson.org/

e.g.  a GeoJSON object is:
```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```
Where IGeoJSON corresponds to that entire object, and IGeometry is an interface for the embedded "geometry" object.

**Comment by RELNO** [comment]
sure, it's only that 'I'+n can easily be read as l ,1 or not at all..

**Comment by agrignard** [comment]
"I" stands for Interface. Personally, I am used to have "I" when declaring an interface but it seems to have some debat about this and different convention

e.g
https://github.com/Microsoft/TypeScript-Handbook/issues/121

**Comment by RELNO** [comment]
I for interface is a common C#/.net convention, though personally I was always confused by overlooking it an inferring a class instead. In any case, looks like MS itself prefer not to use 'I' for interface in TypeScript: https://github.com/Microsoft/TypeScript-Handbook/issues/121

Like tabs vs spaces, it's only a convention. If you all like it, I'll survive ;)

**Comment by RELNO** [comment]
closing for now, will open after convention discussion
